import {USERS_URL} from '../constants';
import { apiSlice } from './apiSlice';

export const usersApiSlice=apiSlice.injectEndpoints({//The `injectEndpoints` function is used to add new endpoints to an existing API slice. It takes an object as an argument that contains the new endpoints to be added to the API slice.
    endpoints:(builder)=>({//define the API endpoints that your application will interact with
        login:builder.mutation({//The `getProducts` endpoint is defined using the `builder.query` method. This method is used to define a query endpoint that fetches data from the specified URL.
            query:(data)=>({
                url: `${USERS_URL}/auth`,//fetch data wihtout axios
                method:'POST',
                body:data,
            }),
        }),
    }),
});

/* it is  exporting a specific hook called `useGetProductsQuery` from the `productsApiSlice` object. This hook is generated by the `apiSlice`
and `injectEndpoints` functions to provide access to the `getProducts` endpoint defined in the API slice. */
export const {useLoginMutation}=usersApiSlice;